"""Utility helpers shared across the manifold."""

from .events import (
    emit_chat_message,
    emit_citation,
    emit_completion,
    emit_error,
    emit_status,
    emit_usage_delta,
    merge_usage_stats,
    wrap_code_block,
    wrap_event_emitter,
)
from .logging import (
    SessionLogger,
    clear_session_logs,
    configure_logging,
    consume_session_logs,
    current_chat_id,
    current_log_level,
    current_message_id,
    current_session_id,
    current_user_id,
    get_session_logs,
    reset_session,
    session_logging,
    set_session,
    truncate_for_log,
)

__all__ = [
    "SessionLogger",
    "set_session",
    "reset_session",
    "session_logging",
    "clear_session_logs",
    "consume_session_logs",
    "get_session_logs",
    "configure_logging",
    "current_session_id",
    "current_chat_id",
    "current_message_id",
    "current_user_id",
    "current_log_level",
    "truncate_for_log",
    "emit_chat_message",
    "emit_citation",
    "emit_completion",
    "emit_error",
    "emit_status",
    "emit_usage_delta",
    "merge_usage_stats",
    "wrap_code_block",
    "wrap_event_emitter",
]
