"""Utility helpers shared across the manifold."""

from .events import (
    emit_chat_message,
    emit_citation,
    emit_completion,
    emit_error,
    emit_status,
    emit_usage_delta,
    merge_usage_stats,
    wrap_code_block,
    wrap_event_emitter,
)
from .logging import (
    SessionLogger,
    OWUI_CHAT_ID,
    OWUI_LOG_LEVEL,
    OWUI_MESSAGE_ID,
    OWUI_SESSION_ID,
    OWUI_USER_ID,
    clear_session_logs,
    configure_logging,
    consume_session_logs,
    get_session_logs,
    logging_context,
    pop_logging_context,
    push_logging_context,
    truncate_for_log,
)

__all__ = [
    "SessionLogger",
    "push_logging_context",
    "pop_logging_context",
    "logging_context",
    "clear_session_logs",
    "consume_session_logs",
    "get_session_logs",
    "configure_logging",
    "OWUI_SESSION_ID",
    "OWUI_CHAT_ID",
    "OWUI_MESSAGE_ID",
    "OWUI_USER_ID",
    "OWUI_LOG_LEVEL",
    "truncate_for_log",
    "emit_chat_message",
    "emit_citation",
    "emit_completion",
    "emit_error",
    "emit_status",
    "emit_usage_delta",
    "merge_usage_stats",
    "wrap_code_block",
    "wrap_event_emitter",
]
