"""Core building blocks: errors, logging, model catalog, markers, and message helpers."""

from openai_responses_manifold.core.errors import (  # noqa: F401
    ManifoldError,
    OpenAIStreamError,
    PersistenceError,
    RoutingError,
    ToolExecutionError,
)
from openai_responses_manifold.core.logging import (  # noqa: F401
    OWUI_CHAT_ID,
    OWUI_LOG_LEVEL,
    OWUI_MESSAGE_ID,
    OWUI_SESSION_ID,
    OWUI_USER_ID,
    clear_session_logs,
    configure_logging,
    consume_session_logs,
    get_logger,
    get_session_logs,
    logging_context,
    pop_logging_context,
    push_logging_context,
    truncate_for_log,
)
from openai_responses_manifold.core.markers import (  # noqa: F401
    ULID_LENGTH,
    contains_marker,
    create_marker,
    extract_markers,
    generate_item_id,
    parse_marker,
    split_text_by_markers,
    wrap_marker,
)
from openai_responses_manifold.core.messages import (  # noqa: F401
    assistant_text_item,
    developer_message,
    normalize_user_blocks,
    user_blocks_to_responses_items,
)
from openai_responses_manifold.core.model_catalog import (  # noqa: F401
    MODEL_ALIASES,
    MODEL_FEATURES,
    alias_defaults,
    base_model,
    features,
    normalize,
    supports,
)

__all__ = [
    "MODEL_FEATURES",
    "MODEL_ALIASES",
    "alias_defaults",
    "features",
    "supports",
    "normalize",
    "base_model",
    "ULID_LENGTH",
    "contains_marker",
    "create_marker",
    "extract_markers",
    "generate_item_id",
    "parse_marker",
    "split_text_by_markers",
    "wrap_marker",
    "assistant_text_item",
    "developer_message",
    "normalize_user_blocks",
    "user_blocks_to_responses_items",
    "ManifoldError",
    "OpenAIStreamError",
    "PersistenceError",
    "RoutingError",
    "ToolExecutionError",
    "OWUI_SESSION_ID",
    "OWUI_CHAT_ID",
    "OWUI_MESSAGE_ID",
    "OWUI_USER_ID",
    "OWUI_LOG_LEVEL",
    "clear_session_logs",
    "configure_logging",
    "consume_session_logs",
    "get_logger",
    "get_session_logs",
    "logging_context",
    "pop_logging_context",
    "push_logging_context",
    "truncate_for_log",
]
