"""
title: OpenAI Responses API Manifold
id: openai_responses
author: Justin Kropp
author_url: https://github.com/jrkropp
git_url: https://github.com/jrkropp/open-webui-developer-toolkit/blob/main/functions/pipes/openai_responses_manifold/openai_responses_manifold.py
description: OpenAI Responses API Manifold
required_open_webui_version: 0.6.28
requirements: aiohttp, fastapi, pydantic>=2
version: 0.9.7
license: MIT

NOTES - PLEASE READ:
This is an experimental restructure build that modularizes the pipe under src/ and re-bundles it into a single file.
Use the version in the alpha-preview or main branches instead.
"""

# NOTE: This file is generated by scripts/build.py.
# The source code lives in src/openai_responses_manifold/ as multiple modules.
# At build time, those modules are bundled into this single file for Open WebUI.
# For the development layout and more details, see README.md.
#
# Logical module layout (source → sections below):
# - model_catalog.py          Single source of truth for OpenAI model capabilities.
# - settings.py               Shared pipe settings and defaults.
# - main.py                   Open WebUI pipe implementation that delegates to the Responses engine.
# - engine.py                 Streaming and tool orchestration engine for the Responses manifold.
# - core/api_models.py        Pydantic request bodies for the Completions and Responses APIs.
# - core/ids.py               Model identifier normalization helpers (prefix/dot/date safe).
# - core/capabilities.py      Model capability registry described in the Developer Guide v2.
# - core/messages.py          Helpers for converting OpenWebUI message blocks to Responses items.
# - core/markers.py           Helpers for encoding/decoding hidden response markers.
# - core/errors.py            Typed exceptions referenced throughout the manifold.
# - services/history.py       Persistence and reconstruction services for Responses items.
# - services/tools.py         Tool declaration and execution helpers.
# - services/routing.py       Helper model routing for auto variants.
# - infra/openwebui_store.py  Persistence helpers for storing Responses items in OpenWebUI.
# - infra/openai_client.py    aiohttp-backed client for the OpenAI Responses API.
# - utils/logging.py          Session-scoped logging helpers with a single namespace and context injection.
# - utils/events.py           Utility functions for emitting OpenWebUI events.

# fmt: off
# Open WebUI runs Black on upload; disabling fmt keeps this bundle readable in that UI.

from __future__ import annotations

# === model_catalog.py ===
"""Single source of truth for OpenAI model capabilities.

If you're adding or modifying supported models, edit this file.
"""

EMPTY_FEATURES: frozenset[str] = frozenset()

# Update MODEL_FEATURES whenever OpenAI adds or removes model capabilities.
MODEL_FEATURES: dict[str, frozenset[str]] = {
    "gpt-5-auto": frozenset({"function_calling", "reasoning", "reasoning_summary", "web_search_tool", "image_gen_tool", "verbosity"}),
    "gpt-5.1": frozenset({"function_calling", "reasoning", "reasoning_summary", "web_search_tool", "image_gen_tool", "verbosity"}),
    "gpt-5": frozenset({"function_calling", "reasoning", "reasoning_summary", "web_search_tool", "image_gen_tool", "verbosity"}),
    "gpt-5-mini": frozenset({"function_calling", "reasoning", "reasoning_summary", "web_search_tool", "image_gen_tool", "verbosity"}),
    "gpt-5-nano": frozenset({"function_calling", "reasoning", "reasoning_summary", "web_search_tool", "image_gen_tool", "verbosity"}),
    "gpt-4.1": frozenset({"function_calling", "web_search_tool", "image_gen_tool"}),
    "gpt-4.1-mini": frozenset({"function_calling", "web_search_tool", "image_gen_tool"}),
    "gpt-4.1-nano": frozenset({"function_calling", "image_gen_tool"}),
    "gpt-4o": frozenset({"function_calling", "web_search_tool", "image_gen_tool"}),
    "gpt-4o-mini": frozenset({"function_calling", "web_search_tool", "image_gen_tool"}),
    "o3": frozenset({"function_calling", "reasoning", "reasoning_summary"}),
    "o3-mini": frozenset({"function_calling", "reasoning", "reasoning_summary"}),
    "o3-pro": frozenset({"function_calling", "reasoning"}),
    "o4-mini": frozenset({"function_calling", "reasoning", "reasoning_summary", "web_search_tool"}),
    "o3-deep-research": frozenset({"function_calling", "reasoning", "reasoning_summary", "deep_research"}),
    "o4-mini-deep-research": frozenset({"function_calling", "reasoning", "reasoning_summary", "deep_research"}),
    "gpt-5.1-chat-latest": frozenset({"function_calling", "web_search_tool"}),
    "gpt-5-chat-latest": frozenset({"function_calling", "web_search_tool"}),
    "chatgpt-4o-latest": EMPTY_FEATURES,
}

# Add entries to MODEL_ALIASES for any pseudo-model name users can pick.
# Each alias is a preset that points to a base model and optional default params,
# e.g. gpt-5-thinking-high -> gpt-5 with reasoning effort fixed to high.
MODEL_ALIASES: dict[str, dict[str, dict | str]] = {
    "gpt-5.1-thinking": {"base_model": "gpt-5.1"},
    "gpt-5.1-thinking-minimal": {"base_model": "gpt-5.1", "params": {"reasoning": {"effort": "minimal"}}},
    "gpt-5.1-thinking-high": {"base_model": "gpt-5.1", "params": {"reasoning": {"effort": "high"}}},
    "gpt-5-thinking": {"base_model": "gpt-5"},
    "gpt-5-thinking-minimal": {"base_model": "gpt-5", "params": {"reasoning": {"effort": "minimal"}}},
    "gpt-5-thinking-high": {"base_model": "gpt-5", "params": {"reasoning": {"effort": "high"}}},
    "gpt-5-thinking-mini": {"base_model": "gpt-5-mini"},
    "gpt-5-thinking-mini-minimal": {"base_model": "gpt-5-mini", "params": {"reasoning": {"effort": "minimal"}}},
    "gpt-5-thinking-mini-high": {"base_model": "gpt-5-mini", "params": {"reasoning": {"effort": "high"}}},
    "gpt-5-thinking-nano": {"base_model": "gpt-5-nano"},
    "gpt-5-thinking-nano-minimal": {"base_model": "gpt-5-nano", "params": {"reasoning": {"effort": "minimal"}}},
    "gpt-5-thinking-nano-high": {"base_model": "gpt-5-nano", "params": {"reasoning": {"effort": "high"}}},
    "o3-mini-high": {"base_model": "o3-mini", "params": {"reasoning": {"effort": "high"}}},
    "o4-mini-high": {"base_model": "o4-mini", "params": {"reasoning": {"effort": "high"}}},
}

__all__ = ["EMPTY_FEATURES", "MODEL_FEATURES", "MODEL_ALIASES"]

# === settings.py ===
"""Shared pipe settings and defaults."""

import os
from typing import Literal, cast

from pydantic import BaseModel, Field

_PIPE_LOG_LEVELS: tuple[Literal["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"], ...] = (
    "DEBUG",
    "INFO",
    "WARNING",
    "ERROR",
    "CRITICAL",
)
_default_pipe_log_level = (os.getenv("GLOBAL_LOG_LEVEL", "INFO") or "INFO").upper()
if _default_pipe_log_level not in _PIPE_LOG_LEVELS:
    _default_pipe_log_level = "INFO"
DEFAULT_PIPE_LOG_LEVEL = cast(
    Literal["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"], _default_pipe_log_level
)


class PipeValves(BaseModel):
    BASE_URL: str = Field(
        default=((os.getenv("OPENAI_API_BASE_URL") or "").strip() or "https://api.openai.com/v1"),
        description="The base URL to use with the OpenAI SDK. Defaults to the official OpenAI API endpoint. Supports LiteLLM and other custom endpoints.",
    )
    API_KEY: str = Field(
        default=(os.getenv("OPENAI_API_KEY") or "").strip() or "sk-xxxxx",
        description="Your OpenAI API key. Defaults to the value of the OPENAI_API_KEY environment variable.",
    )
    MODEL_ID: str = Field(
        default="gpt-5-auto, gpt-5-chat-latest, gpt-5-thinking, gpt-5-thinking-high, gpt-5-thinking-minimal, gpt-4.1-nano, chatgpt-4o-latest, o3, gpt-4o",
        description=(
            "Comma separated OpenAI model IDs. Each ID becomes a model entry in WebUI. "
            "Supports all official OpenAI model IDs and pseudo IDs (see README.md for full list)."
        ),
    )
    REASONING_SUMMARY: Literal["auto", "concise", "detailed", "disabled"] = Field(
        default="disabled",
        description="REQUIRES VERIFIED OPENAI ORG. Visible reasoning summary (auto | concise | detailed | disabled). Works on gpt-5, o3, o4-mini; ignored otherwise. Docs: https://platform.openai.com/docs/api-reference/responses/create#responses-create-reasoning",
    )
    PERSIST_REASONING_TOKENS: Literal["response", "conversation", "disabled"] = Field(
        default="disabled",
        description="REQUIRES VERIFIED OPENAI ORG. If verified, highly recommend using 'response' or 'conversation' for best results. If `disabled` (default) = never request encrypted reasoning tokens; if `response` = request tokens so the model can carry reasoning across tool calls for the current response; If `conversation` = also persist tokens for future messages in this chat (higher token usage; quality may vary).",
    )
    PERSIST_TOOL_RESULTS: bool = Field(
        default=True,
        description="Persist tool call results across conversation turns. When disabled, tool results are not stored in the chat history.",
    )
    PARALLEL_TOOL_CALLS: bool = Field(
        default=True,
        description="Whether tool calls can be parallelized. Defaults to True if not set. Read more: https://platform.openai.com/docs/api-reference/responses/create#responses-create-parallel_tool_calls",
    )
    ENABLE_STRICT_TOOL_CALLING: bool = Field(
        default=True,
        description=(
            "When True, converts Open WebUI registry tools to strict JSON Schema for OpenAI tools, "
            "enforcing explicit types, required fields, and disallowing additionalProperties."
        ),
    )
    MAX_TOOL_CALLS: int | None = Field(
        default=None,
        description=(
            "Maximum number of individual tool or function calls the model can make "
            "within a single response. Applies to the total number of calls across "
            "all built-in tools. Further tool-call attempts beyond this limit will be ignored."
        ),
    )
    MAX_FUNCTION_CALL_LOOPS: int = Field(
        default=10,
        description=(
            "Maximum number of full execution cycles (loops) allowed per request. "
            "Each loop involves the model generating one or more function/tool calls, "
            "executing all requested functions, and feeding the results back into the model. "
            "Looping stops when this limit is reached or when the model no longer requests "
            "additional tool or function calls."
        ),
    )
    ENABLE_WEB_SEARCH_TOOL: bool = Field(
        default=False,
        description="Enable OpenAI's built-in 'web_search' tool when supported (gpt-4.1, gpt-4.1-mini, gpt-4o, gpt-4o-mini, o3, o4-mini, o4-mini-high). NOTE: This appears to disable parallel tool calling. Read more: https://platform.openai.com/docs/guides/tools-web-search?api-mode=responses",
    )
    WEB_SEARCH_CONTEXT_SIZE: Literal["low", "medium", "high", None] = Field(
        default="medium",
        description="Specifies the OpenAI web search context size: low | medium | high. Default is 'medium'. Affects cost, quality, and latency. Only used if ENABLE_WEB_SEARCH_TOOL=True.",
    )
    WEB_SEARCH_USER_LOCATION: str | None = Field(
        default=None,
        description='User location for web search context. Leave blank to disable. Must be in valid JSON format according to OpenAI spec.  E.g., {"type": "approximate","country": "US","city": "San Francisco","region": "CA"}.',
    )
    REMOTE_MCP_SERVERS_JSON: str | None = Field(
        default=None,
        description=(
            "[EXPERIMENTAL] A JSON-encoded list (or single JSON object) defining one or more "
            "remote MCP servers to be automatically attached to each request. This can be useful "
            "for globally enabling tools across all chats."
        ),
    )
    TRUNCATION: Literal["auto", "disabled"] = Field(
        default="auto",
        description="OpenAI truncation strategy. 'auto' drops middle context items if the conversation exceeds the context window; 'disabled' returns a 400 error instead.",
    )
    PROMPT_CACHE_KEY: Literal["id", "email"] = Field(
        default="id",
        description="Controls which user identifier is sent in the 'user' parameter to OpenAI.",
    )
    LOG_LEVEL: Literal["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"] = Field(
        default=DEFAULT_PIPE_LOG_LEVEL,
        description="Select logging level. Recommend INFO or WARNING for production use.",
    )


class UserValves(BaseModel):
    LOG_LEVEL: Literal["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL", "INHERIT"] = Field(
        default="INHERIT",
        description="Select logging level. 'INHERIT' uses the pipe default.",
    )

# === main.py ===
"""Open WebUI pipe implementation that delegates to the Responses engine."""

import inspect
import logging
from collections.abc import Awaitable, Callable
from typing import Any

from fastapi import Request
from open_webui.models.models import ModelForm, Models

# [build.py] internal imports removed in monolith:
# from .core.api_models import CompletionsBody, ResponsesBody
# from .core.capabilities import supports
# from .engine import EventEmitter, ResponsesEngine
# from .infra import ItemStore, OpenAIResponsesClient
# from .services import HistoryBuilder, build_tools, route_auto_model
# from .settings import PipeValves, UserValves
# from .utils import SessionLogger, reset_session, set_session


class Pipe:
    class Valves(PipeValves):
        """Admin-level valve configuration."""

    class UserValves(UserValves):
        """Per-user valve overrides."""

    def __init__(self) -> None:
        self.type = "manifold"
        self.id = "openai_responses"
        self.valves = self.Valves()
        self.logger = SessionLogger.get_logger(__name__)
        self.store = ItemStore()
        self.engine = ResponsesEngine(
            client=OpenAIResponsesClient(),
            item_store=self.store,
            logger=self.logger,
        )

    async def pipes(self) -> list[dict[str, str]]:
        model_ids = [
            model_id.strip() for model_id in self.valves.MODEL_ID.split(",") if model_id.strip()
        ]
        return [{"id": model_id, "name": f"OpenAI: {model_id}"} for model_id in model_ids]

    async def pipe(
        self,
        body: dict[str, Any],
        __user__: dict[str, Any],
        __request__: Request,
        __event_emitter__: EventEmitter,
        __event_call__: Callable[[dict[str, Any]], Awaitable[Any]] | None,
        __metadata__: dict[str, Any],
        __tools__: list[dict[str, Any]] | dict[str, Any] | None,
        __task__: dict[str, Any] | None = None,
        __task_body__: dict[str, Any] | None = None,
    ) -> Awaitable[str] | str | None:
        valves = self._merge_valves(
            self.valves, self.UserValves.model_validate(__user__.get("valves", {}))
        )
        openwebui_model_id = __metadata__.get("model", {}).get("id", "")
        user_identifier = __user__[valves.PROMPT_CACHE_KEY]
        features = __metadata__.get("features", {}).get("openai_responses", {})

        tokens = set_session(
            __metadata__.get("session_id"),
            getattr(logging, valves.LOG_LEVEL.upper(), logging.INFO),
            chat_id=__metadata__.get("chat_id"),
            message_id=__metadata__.get("message_id"),
            user_id=__metadata__.get("user_id"),
        )
        self.logger.debug(
            "Session context resolved: session_id=%s chat_id=%s message_id=%s user_id=%s log_level=%s",
            __metadata__.get("session_id"),
            __metadata__.get("chat_id"),
            __metadata__.get("message_id"),
            __metadata__.get("user_id"),
            valves.LOG_LEVEL,
        )

        if __event_call__:
            await __event_call__(self._status_unclamp_script())

        completions_body = CompletionsBody.model_validate(body)
        history_input = self._build_history_input(
            completions_body.messages,
            __metadata__,
        )
        extra_params: dict[str, Any] = {
            "truncation": valves.TRUNCATION,
            "user": user_identifier,
        }
        chat_id_value = __metadata__.get("chat_id")
        if isinstance(chat_id_value, str):
            extra_params["chat_id"] = chat_id_value
        if valves.MAX_TOOL_CALLS is not None:
            extra_params["max_tool_calls"] = valves.MAX_TOOL_CALLS

        responses_body = ResponsesBody.from_completions(
            completions_body=completions_body,
            history_input=history_input,
            **extra_params,
        )

        if __task__:
            self.logger.info("Detected task model: %s", __task__)
            return await self.engine.run_task_model(responses_body.model_dump(), valves)

        __tools__ = await __tools__ if inspect.isawaitable(__tools__) else __tools__
        tool_registry: dict[str, dict[str, Any]] | None = (
            __tools__ if isinstance(__tools__, dict) else None
        )
        tools = build_tools(
            responses_body,
            valves,
            openwebui_tools=tool_registry,
            features=features,
            extra_tools=getattr(completions_body, "extra_tools", None),
        )

        if tools and supports("function_calling", responses_body.model):
            model = Models.get_model_by_id(openwebui_model_id)
            if model:
                params = dict(model.params or {})
                if params.get("function_calling") != "native":
                    await self.engine.emit_notification(
                        __event_emitter__,
                        content=f"Enabling native function calling for model: {openwebui_model_id}. Please re-run your query.",
                        level="info",
                    )
                    params["function_calling"] = "native"
                    form_data = model.model_dump()
                    form_data["params"] = params
                    Models.update_model_by_id(openwebui_model_id, ModelForm(**form_data))

        if openwebui_model_id.endswith(".gpt-5-auto-dev"):
            responses_body = await route_auto_model(
                self.engine.client,
                router_model="gpt-4.1-mini",
                responses_body=responses_body,
                valves=valves,
                tools=tools,
                event_emitter=__event_emitter__,
            )
        elif openwebui_model_id.endswith(".gpt-5-auto"):
            responses_body.model = "gpt-5-chat-latest"
            await self.engine.emit_notification(
                __event_emitter__,
                content="Model router coming soon — using gpt-5-chat-latest (GPT-5 Fast).",
                level="warning",
            )

        if supports("function_calling", responses_body.model):
            responses_body.tools = tools

        if (
            supports("reasoning_summary", responses_body.model)
            and valves.REASONING_SUMMARY != "disabled"
        ):
            reasoning_params = dict(responses_body.reasoning or {})
            reasoning_params["summary"] = valves.REASONING_SUMMARY
            responses_body.reasoning = reasoning_params

        if (
            supports("reasoning", responses_body.model)
            and valves.PERSIST_REASONING_TOKENS != "disabled"
            and responses_body.store is False
        ):
            responses_body.include = responses_body.include or []
            if "reasoning.encrypted_content" not in responses_body.include:
                responses_body.include.append("reasoning.encrypted_content")

        if any(
            isinstance(tool, dict) and tool.get("type") == "web_search"
            for tool in (responses_body.tools or [])
        ):
            responses_body.parallel_tool_calls = False
        else:
            responses_body.parallel_tool_calls = getattr(valves, "PARALLEL_TOOL_CALLS", True)

        try:
            return await self.engine.run_streaming_turn(
                responses_body,
                valves=valves,
                metadata=__metadata__,
                event_emitter=__event_emitter__,
                tool_registry=tool_registry or {},
            )
        finally:
            reset_session(tokens)

    def _merge_valves(self, pipe_valves: PipeValves, user_valves: UserValves) -> PipeValves:
        merged = pipe_valves.model_copy(deep=True)
        if user_valves.LOG_LEVEL != "INHERIT":
            merged.LOG_LEVEL = user_valves.LOG_LEVEL
        return merged

    def _build_history_input(
        self,
        messages: list[dict[str, Any]],
        metadata: dict[str, Any],
    ) -> list[dict[str, Any]]:
        chat_id = metadata.get("chat_id")
        openwebui_model_id = metadata.get("model", {}).get("id")

        def _resolver(item_ids: list[str], resolver_chat: str | None, model_id: str | None) -> dict[str, dict[str, Any]]:
            target_chat = resolver_chat or chat_id or ""
            target_model = model_id or openwebui_model_id
            return self.store.load_items(
                target_chat,
                item_ids,
                model_id=target_model,
            )

        builder = HistoryBuilder(resolve_items=_resolver)
        return builder.build_input_from_messages(
            messages,
            chat_id=chat_id,
            openwebui_model_id=openwebui_model_id,
        )

    @staticmethod
    def _status_unclamp_script() -> dict[str, Any]:
        return {
            "type": "execute",
            "data": {
                "code": """
                (() => {
                if (document.getElementById("owui-status-unclamp")) return "ok";
                const style = document.createElement("style");
                style.id = "owui-status-unclamp";
                style.textContent = `
                    .status-description .line-clamp-1,
                    .status-description .text-base.line-clamp-1,
                    .status-description .text-gray-500.text-base.line-clamp-1 {
                    display: block !important;
                    overflow: visible !important;
                    -webkit-line-clamp: unset !important;
                    -webkit-box-orient: initial !important;
                    white-space: pre-wrap !important;
                    word-break: break-word;
                    }

                    .status-description .text-base::first-line,
                    .status-description .text-gray-500.text-base::first-line {
                    font-weight: 500 !important;
                    }
                `;

                document.head.appendChild(style);
                return "ok";
                })();
                """,
            },
        }

# === engine.py ===
"""Streaming and tool orchestration engine for the Responses manifold."""

import asyncio
import json
import logging
import random
from collections.abc import Awaitable, Callable
from time import perf_counter
from typing import Any, Literal

from open_webui.models.chats import Chats

# [build.py] internal imports removed in monolith:
# from .core.api_models import ResponsesBody
# from .core.capabilities import supports
# from .infra import ItemStore, OpenAIResponsesClient
# from .services.history import HistoryPersistence
# from .services.tools import execute_tool_calls
# from .utils import (
#     SessionLogger,
#     clear_session_logs,
#     current_session_id,
#     emit_chat_message,
#     emit_citation,
#     emit_completion,
#     emit_error,
#     emit_status,
#     get_session_logs,
#     merge_usage_stats,
#     truncate_for_log,
#     wrap_code_block,
#     wrap_event_emitter,
# )

EventEmitter = Callable[[dict[str, Any]], Awaitable[None]]


class ResponsesEngine:
    """Encapsulates the streaming and tool orchestration logic."""

    def __init__(
        self,
        *,
        client: OpenAIResponsesClient | None = None,
        item_store: ItemStore | None = None,
        history_persistence: HistoryPersistence | None = None,
        logger: logging.Logger | None = None,
    ) -> None:
        self.client = client or OpenAIResponsesClient()
        self.store = item_store or ItemStore()
        self.history_persistence = history_persistence or HistoryPersistence(self.store)
        self.logger = logger or SessionLogger.get_logger(__name__)

    async def run_streaming_turn(
        self,
        body: ResponsesBody,
        *,
        valves: Any,
        metadata: dict[str, Any],
        event_emitter: EventEmitter,
        tool_registry: dict[str, dict[str, Any]] | None = None,
    ) -> str:
        tool_registry = tool_registry or {}
        assistant_message = ""
        total_usage: dict[str, Any] = {}
        ordinal_by_url: dict[str, int] = {}
        emitted_citations: list[dict[str, Any]] = []
        openwebui_model = metadata.get("model", {}).get("id", "")

        thinking_tasks = self._schedule_reasoning_statuses(body, event_emitter)
        final_response: dict[str, Any] | None = None

        model_router_result = body.model_router_result
        if model_router_result:
            body.model_router_result = None
            explanation = model_router_result.get("explanation", "")
            await emit_status(
                event_emitter,
                f"Routing to {model_router_result.get('model')} (effort: {model_router_result.get('reasoning_effort')})\nExplanation: {explanation}",
            )

        start_time = perf_counter()
        error_occurred = False
        try:
            max_loops = getattr(valves, "MAX_FUNCTION_CALL_LOOPS", 10)
            for _ in range(max_loops):
                final_response = None
                async for event in self.client.stream(
                    body.model_dump(exclude_none=True),
                    api_key=valves.API_KEY,
                    base_url=valves.BASE_URL,
                ):
                    event_type = event.get("type")
                    if self.logger.isEnabledFor(logging.DEBUG):
                        self.logger.debug("Received event: %s", event_type)
                        if not str(event_type).endswith(".delta"):
                            payload, truncated = truncate_for_log(
                                json.dumps(event, ensure_ascii=False), limit=3000
                            )
                            suffix = " (truncated)" if truncated else ""
                            self.logger.debug("Event data%s: %s", suffix, payload)

                    if event_type == "response.output_text.delta":
                        delta = event.get("delta", "")
                        if delta:
                            assistant_message += delta
                            await emit_chat_message(event_emitter, assistant_message)
                    elif event_type == "response.output_text.done":
                        final_response = event
                        await self._cancel_tasks(thinking_tasks)
                    elif event_type == "response.error":
                        await self._cancel_tasks(thinking_tasks)
                        error_occurred = True
                        await self._handle_stream_error(
                            event_emitter,
                            event.get("error", {}).get("message", "OpenAI returned an error."),
                        )
                        break
                    elif event_type == "response.completed_with_error":
                        await self._cancel_tasks(thinking_tasks)
                        error_occurred = True
                        await self._handle_stream_error(
                            event_emitter,
                            event.get("error", {}).get("message", "OpenAI returned an error."),
                        )
                        break
                    elif event_type == "response.completed":
                        final_response = event.get("response") or final_response or event
                        await self._cancel_tasks(thinking_tasks)
                        break
                    elif event_type == "response.output_text.delta.truncated":
                        continue
                    elif event_type == "response.usage_delta":
                        total_usage = merge_usage_stats(total_usage, event.get("delta", {}))
                    elif event_type == "response.output_items.delta":
                        await self._handle_output_items_delta(
                            event,
                            event_emitter,
                            emitted_citations,
                            ordinal_by_url,
                            metadata,
                        )
                    elif event_type == "response.tool_call_arguments.delta":
                        partial_args = event.get("delta", "")
                        if partial_args:
                            event.setdefault("event_metadata", {})
                            event["event_metadata"]["partial_arguments"] = partial_args
                    elif event_type == "response.output_items.done":
                        final_response = event.get("response") or final_response or event
                        await self._cancel_tasks(thinking_tasks)
                    elif event_type == "response.message.delta":
                        await self._handle_message_delta(event, emitted_citations, ordinal_by_url)

                if final_response and not total_usage:
                    usage_from_response = self._extract_usage_from_final_response(
                        final_response
                    )
                    if usage_from_response:
                        total_usage = merge_usage_stats(total_usage, usage_from_response)

                if error_occurred or not final_response:
                    break

                if not supports("function_calling", body.model):
                    break
                call_items = (final_response or {}).get("output", [])
                tool_calls = [item for item in call_items if item.get("type") == "function_call"]
                if not tool_calls:
                    break
                function_outputs = await execute_tool_calls(tool_calls, tool_registry)
                if not function_outputs:
                    break
                existing_input = list(body.input) if isinstance(body.input, list) else []
                body.input = existing_input + function_outputs

            respond_time = perf_counter() - start_time
            self.logger.info("Total streaming duration: %.2f seconds", respond_time)

        except Exception as exc:  # pragma: no cover
            await self._cancel_tasks(thinking_tasks)
            error_occurred = True
            await self._handle_stream_error(event_emitter, str(exc))

        finally:
            await self._flush_logs(event_emitter, valves, emitted_citations)
            await emit_completion(
                event_emitter,
                content=assistant_message,
                usage=total_usage or None,
                done=True,
            )
            chat_id = metadata.get("chat_id")
            message_id = metadata.get("message_id")
            if chat_id and message_id and emitted_citations:
                Chats.upsert_message_to_chat_by_id_and_message_id(
                    chat_id, message_id, {"sources": emitted_citations}
                )

        return assistant_message

    async def run_nonstreaming_turn(
        self,
        body: ResponsesBody,
        *,
        valves: Any,
        metadata: dict[str, Any],
        event_emitter: EventEmitter,
        tool_registry: dict[str, dict[str, Any]] | None = None,
    ) -> str:
        body.stream = True
        wrapped_emitter = wrap_event_emitter(
            event_emitter, suppress_chat_messages=True, suppress_completion=False
        )
        return await self.run_streaming_turn(
            body,
            valves=valves,
            metadata=metadata,
            event_emitter=wrapped_emitter,
            tool_registry=tool_registry,
        )

    async def run_task_model(
        self,
        body: dict[str, Any],
        valves: Any,
    ) -> str:
        task_body = {
            "model": body.get("model"),
            "instructions": body.get("instructions", ""),
            "input": body.get("input", ""),
            "stream": False,
            "store": False,
        }
        response = await self.client.create(
            task_body, api_key=valves.API_KEY, base_url=valves.BASE_URL
        )
        text_parts: list[str] = []
        for item in response.get("output", []):
            if item.get("type") != "message":
                continue
            for content in item.get("content", []):
                if content.get("type") == "output_text":
                    text_parts.append(content.get("text", ""))
        return "".join(text_parts)

    async def emit_notification(
        self,
        event_emitter: EventEmitter | None,
        content: str,
        *,
        level: Literal["info", "success", "warning", "error"] = "info",
    ) -> None:
        await emit_status(event_emitter, content, action=level)

    async def emit_error(
        self,
        event_emitter: EventEmitter | None,
        error_obj: Exception | str,
        *,
        show_error_message: bool = True,
        done: bool = False,
    ) -> None:
        if not show_error_message:
            return
        await emit_error(event_emitter, str(error_obj), done=done)

    def _schedule_reasoning_statuses(
        self, body: ResponsesBody, event_emitter: EventEmitter
    ) -> list[asyncio.Task[Any]]:
        if not supports("reasoning", body.model):
            return []

        async def _later(delay: float, msg: str) -> None:
            await asyncio.sleep(delay)
            await emit_status(event_emitter, msg)

        tasks: list[asyncio.Task[Any]] = []
        for delay, msg in [
            (0, "Thinking…"),
            (1.5, "Reading the user's question…"),
            (4.0, "Gathering my thoughts…"),
            (6.0, "Exploring possible responses…"),
            (7.0, "Building a plan…"),
        ]:
            tasks.append(asyncio.create_task(_later(delay + random.uniform(0, 0.5), msg)))
        return tasks

    async def _cancel_tasks(self, tasks: list[asyncio.Task[Any]]) -> None:
        if not tasks:
            return
        to_cancel = list(tasks)
        tasks.clear()
        for task in to_cancel:
            task.cancel()
        await asyncio.gather(*to_cancel, return_exceptions=True)

    def _extract_usage_from_final_response(
        self, final_response: dict[str, Any]
    ) -> dict[str, Any]:
        if "usage" in final_response:
            usage = final_response.get("usage")
            return usage if isinstance(usage, dict) else {}

        response_payload = final_response.get("response")
        if isinstance(response_payload, dict):
            usage = response_payload.get("usage")
            if isinstance(usage, dict):
                return usage

        return {}

    async def _handle_stream_error(
        self,
        event_emitter: EventEmitter | None,
        message: str,
    ) -> None:
        self.logger.error("Streaming error: %s", message)
        await emit_error(event_emitter, message, done=False)

    async def _flush_logs(
        self,
        event_emitter: EventEmitter | None,
        valves: Any,
        emitted_citations: list[dict[str, Any]] | None = None,
    ) -> None:
        session_id = current_session_id.get()
        if not session_id:
            return
        logs = get_session_logs(session_id)
        if logs:
            log_text = "\n".join(logs)
            is_truncated = len(log_text) > 4000
            self.logger.debug(
                "Emitting log citation lines=%d truncated=%s", len(logs), is_truncated
            )
            await emit_citation(event_emitter, log_text, "Logs")
            if emitted_citations is not None:
                snippet = log_text if len(log_text) <= 4000 else log_text[-4000:]
                emitted_citations.append(
                    {
                        "provider": "openai:logs",
                        "id": str(len(emitted_citations) + 1),
                        "title": "Logs",
                        "snippet": snippet,
                        "metadata": {
                            "source": "Logs",
                            "total_lines": len(logs),
                            "truncated": len(snippet) < len(log_text),
                        },
                    }
                )
            clear_session_logs(session_id)

    async def _handle_output_items_delta(
        self,
        event: dict[str, Any],
        event_emitter: EventEmitter,
        emitted_citations: list[dict[str, Any]],
        ordinal_by_url: dict[str, int],
        metadata: dict[str, Any],
    ) -> None:
        items = (event.get("output_items", {}) or {}).get("items", [])
        persistable: list[dict[str, Any]] = []
        for item in items:
            item_type = item.get("type", "")
            item_name = item.get("name", "")
            if not item_type:
                continue
            if item_type == "openai_response.items":
                persistable.append(item)
                continue
            title = ""
            content = ""
            if item_type == "function_call":
                title = f"Running the {item_name} tool…"
                try:
                    arguments = json.loads(item.get("arguments") or "{}")
                except json.JSONDecodeError as exc:
                    self.logger.warning(
                        "Received malformed tool arguments for %s: %s", item_name, exc
                    )
                    await emit_status(
                        event_emitter,
                        "Skipping malformed tool arguments.",
                        action="warning",
                    )
                    continue
                args_formatted = ", ".join(f"{k}={json.dumps(v)}" for k, v in arguments.items())
                content = wrap_code_block(f"{item_name}({args_formatted})", "python")
            elif item_type == "web_search_call":
                action = item.get("action", {}) or {}
                if action.get("type") == "search":
                    query = action.get("query")
                    sources = action.get("sources") or []
                    urls = [source.get("url") for source in sources if source.get("url")]
                    if query:
                        await emit_status(
                            event_emitter,
                            "Searching",
                            action="web_search_queries_generated",
                            queries=[query],
                            done=False,
                        )
                    if urls:
                        await emit_status(
                            event_emitter,
                            "Reading sources…",
                            action="web_search",
                            query=query,
                            urls=urls,
                            done=False,
                        )
                continue
            elif item_type in {
                "response_completion",
                "response.output_text.delta",
                "response_tool_call",
                "typing_status",
            }:
                continue
            else:
                title = f"Processing {item_type}"
                content = json.dumps(item, indent=2, ensure_ascii=False)

            await emit_status(
                event_emitter,
                title,
                action="tool_call",
                content=content,
                done=False,
            )

        if persistable:
            chat_id = metadata.get("chat_id") or ""
            message_id = metadata.get("message_id") or ""
            openwebui_model_id = metadata.get("model", {}).get("id", "") or ""
            hidden_marker = self.history_persistence.persist_items_for_message(
                chat_id,
                message_id,
                persistable,
                model_id=openwebui_model_id,
            )
            if hidden_marker:
                await emit_chat_message(
                    event_emitter,
                    hidden_marker,
                    options={"persist_history": False},
                )

    async def _handle_message_delta(
        self,
        event: dict[str, Any],
        emitted_citations: list[dict[str, Any]],
        ordinal_by_url: dict[str, int],
    ) -> None:
        deltas = event.get("delta", {}).get("content", [])
        for delta in deltas:
            if delta.get("type") == "citations":
                citations = delta.get("citations") or []
                for citation in citations:
                    content_items = citation.get("content") or []
                    for item in content_items:
                        if item.get("type") != "input_text":
                            continue
                        text_value = item.get("text") or ""
                        if not text_value or len(text_value) < 20:
                            continue
                        source_url = citation.get("metadata", {}).get("url")
                        if not source_url:
                            continue
                        ordinal = ordinal_by_url.setdefault(source_url, len(ordinal_by_url) + 1)
                        payload = {
                            "provider": "openai:citation",
                            "id": f"{ordinal}",
                            "title": citation.get("metadata", {}).get("title") or source_url,
                            "link": source_url,
                            "snippet": text_value,
                            "metadata": citation.get("metadata", {}),
                        }
                        emitted_citations.append(payload)


__all__ = ["EventEmitter", "ResponsesEngine"]

# === core/api_models.py ===
"""Pydantic request bodies for the Completions and Responses APIs."""

import json
from typing import Any, Literal

from pydantic import BaseModel, model_validator

# [build.py] internal imports removed in monolith:
# from .capabilities import MODEL_ALIASES, alias_defaults
# from .ids import base_model
# from .messages import (
#     assistant_text_item,
#     developer_message,
#     normalize_user_blocks,
#     user_blocks_to_responses_items,
# )


class CompletionsBody(BaseModel):
    """Request body compatible with OpenAI's legacy Completions API."""

    model: str
    messages: list[dict[str, Any]]
    stream: bool = False

    class Config:
        extra = "allow"


class ResponsesBody(BaseModel):
    """Request body for the OpenAI Responses API."""

    model: str
    input: str | list[dict[str, Any]]
    instructions: str | None = ""
    stream: bool = False
    store: bool | None = False
    temperature: float | None = None
    top_p: float | None = None
    max_output_tokens: int | None = None
    truncation: Literal["auto", "disabled"] | None = None
    reasoning: dict[str, Any] | None = None
    parallel_tool_calls: bool | None = True
    user: str | None = None
    tool_choice: dict[str, Any] | None = None
    tools: list[dict[str, Any]] | None = None
    include: list[str] | None = None
    text: dict[str, Any] | None = None
    model_router_result: dict[str, Any] | None = None

    class Config:
        extra = "allow"

    @model_validator(mode="after")
    def _apply_alias_defaults(self) -> ResponsesBody:
        """Normalize aliases and merge default parameters."""

        orig_model = self.model or ""
        canonical_model = base_model(orig_model, MODEL_ALIASES)
        defaults = alias_defaults(orig_model) or {}

        if canonical_model == orig_model and not defaults:
            return self

        data = json.loads(self.model_dump_json(exclude_none=False))
        data["model"] = canonical_model

        def _deep_overlay(dst: dict[str, Any], src: dict[str, Any]) -> dict[str, Any]:
            for key, value in src.items():
                if isinstance(value, dict):
                    node = dst.get(key)
                    if isinstance(node, dict):
                        _deep_overlay(node, value)
                    else:
                        dst[key] = json.loads(json.dumps(value))
                elif isinstance(value, list):
                    existing = dst.get(key)
                    if isinstance(existing, list):
                        seen: set[tuple[str, str]] = set()
                        merged: list[Any] = []

                        def _make_key(item: Any) -> tuple[str, str]:
                            try:
                                return ("json", json.dumps(item, sort_keys=True))
                            except Exception:
                                return ("id", str(id(item)))

                        for item in existing + value:
                            key_tuple = _make_key(item)
                            if key_tuple not in seen:
                                seen.add(key_tuple)
                                merged.append(item)
                        dst[key] = merged
                    else:
                        dst[key] = list(value)
                else:
                    dst[key] = value
            return dst

        if defaults:
            _deep_overlay(data, defaults)

        for key, value in data.items():
            setattr(self, key, value)
        return self

    @classmethod
    def from_completions(
        cls,
        completions_body: CompletionsBody,
        *,
        history_input: list[dict[str, Any]] | None = None,
        **extra_params: Any,
    ) -> ResponsesBody:
        """Convert a Completions request payload into Responses format."""

        completions_dict = completions_body.model_dump(exclude_none=True)

        unsupported_fields = {
            "frequency_penalty",
            "presence_penalty",
            "seed",
            "logit_bias",
            "logprobs",
            "top_logprobs",
            "n",
            "stop",
            "response_format",
            "suffix",
            "stream_options",
            "audio",
            "function_call",
            "functions",
            "reasoning_effort",
            "max_tokens",
            "tools",
            "extra_tools",
        }

        sanitized_params: dict[str, Any] = {}
        for key, value in completions_dict.items():
            if key in unsupported_fields:
                continue
            sanitized_params[key] = value

        if "max_tokens" in completions_dict:
            sanitized_params["max_output_tokens"] = completions_dict["max_tokens"]

        effort = completions_dict.get("reasoning_effort")
        if effort:
            reasoning = sanitized_params.get("reasoning", {})
            reasoning.setdefault("effort", effort)
            sanitized_params["reasoning"] = reasoning

        instructions = next(
            (
                msg["content"]
                for msg in reversed(completions_dict.get("messages", []))
                if msg.get("role") == "system"
            ),
            None,
        )
        if instructions:
            sanitized_params["instructions"] = instructions

        messages = completions_dict.get("messages")
        if messages is not None:
            sanitized_params.pop("messages", None)
            sanitized_params["input"] = (
                history_input if history_input is not None else _default_input_from_messages(messages)
            )

        return cls(**sanitized_params, **extra_params)


def _default_input_from_messages(messages: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Fallback conversion from OpenWebUI messages when no history builder is provided."""

    input_items: list[dict[str, Any]] = []
    for message in messages:
        role = message.get("role")
        if role == "system":
            continue
        if role == "user":
            blocks = user_blocks_to_responses_items(
                normalize_user_blocks(message.get("content"))
            )
            if blocks:
                input_items.append({"role": "user", "content": blocks})
            continue
        if role == "developer":
            content = message.get("content")
            if isinstance(content, str) and content:
                input_items.append(developer_message(content))
            continue
        if role == "assistant":
            content = message.get("content")
            if isinstance(content, str) and content.strip():
                input_items.append(assistant_text_item(content.strip()))
    return input_items


__all__ = ["CompletionsBody", "ResponsesBody"]

# === core/ids.py ===
"""Model identifier normalization helpers (prefix/dot/date safe)."""

import re
from typing import Mapping

# [build.py] internal imports removed in monolith:
# from ..model_catalog import MODEL_ALIASES, MODEL_FEATURES

_DATE_SUFFIX_RE = re.compile(r"-\d{4}-\d{2}-\d{2}$")
_KNOWN_IDS = frozenset({*MODEL_FEATURES.keys(), *MODEL_ALIASES.keys()})


def normalize(model_id: str) -> str:
    """Normalize identifiers by lowercasing, trimming, and removing prefixes/dates."""

    raw = (model_id or "").strip().lower()
    if not raw:
        return ""
    no_date = _DATE_SUFFIX_RE.sub("", raw)
    if no_date in _KNOWN_IDS:
        return no_date

    dot_index = no_date.find(".")
    if dot_index != -1:
        suffix = _DATE_SUFFIX_RE.sub("", no_date[dot_index + 1 :])
        if suffix in _KNOWN_IDS:
            return suffix

    return no_date


def base_model(
    model_id: str,
    alias_lookup: Mapping[str, Mapping[str, str | dict]] | None = None,
) -> str:
    """Return the canonical base model for a given identifier."""

    alias_map = alias_lookup or MODEL_ALIASES
    normalized = normalize(model_id)
    alias_entry = alias_map.get(normalized)
    if alias_entry:
        base = alias_entry.get("base_model")
        if isinstance(base, str):
            return normalize(base)
    return normalized


__all__ = ["base_model", "normalize"]

# === core/capabilities.py ===
"""Model capability registry described in the Developer Guide v2."""

from copy import deepcopy
from typing import Any

# [build.py] internal imports removed in monolith:
# from ..model_catalog import EMPTY_FEATURES, MODEL_ALIASES, MODEL_FEATURES
# from .ids import base_model, normalize


def alias_defaults(model_id: str) -> dict[str, Any]:
    """Return default parameters defined for a pseudo-model alias."""

    params = MODEL_ALIASES.get(normalize(model_id), {}).get("params")
    return deepcopy(params) if params else {}


def features(model_id: str) -> frozenset[str]:
    """Return the capability set for the canonical base model."""

    canonical = base_model(model_id, MODEL_ALIASES)
    return MODEL_FEATURES.get(canonical, EMPTY_FEATURES)


def supports(feature: str, model_id: str) -> bool:
    """Determine whether the supplied model exposes a feature."""

    return feature in features(model_id)


__all__ = [
    "MODEL_ALIASES",
    "MODEL_FEATURES",
    "alias_defaults",
    "features",
    "supports",
]

# === core/messages.py ===
"""Helpers for converting OpenWebUI message blocks to Responses items."""

from typing import Any


def normalize_user_blocks(content: str | list[dict[str, Any]] | None) -> list[dict[str, Any]]:
    """Return a list of user blocks regardless of how OpenWebUI formatted them."""

    if isinstance(content, str):
        return [{"type": "text", "text": content}]
    if isinstance(content, list):
        return [block for block in content if isinstance(block, dict)]
    return []


def user_blocks_to_responses_items(blocks: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Convert OpenWebUI user blocks into Responses input items."""

    responses: list[dict[str, Any]] = []
    for block in blocks:
        block_type = block.get("type")
        if block_type == "text":
            responses.append({"type": "input_text", "text": block.get("text", "")})
        elif block_type == "image_url":
            url = (block.get("image_url") or {}).get("url")
            if url:
                responses.append({"type": "input_image", "image_url": url})
        elif block_type == "input_file":
            file_id = block.get("file_id")
            if file_id:
                responses.append({"type": "input_file", "file_id": file_id})
    return responses


def assistant_text_item(text: str) -> dict[str, Any]:
    """Generate an assistant output item for plain text segments."""

    return {
        "role": "assistant",
        "content": [
            {
                "type": "output_text",
                "text": text,
            }
        ],
    }


def developer_message(content: str) -> dict[str, Any]:
    """Construct a developer-role message block."""

    return {"role": "developer", "content": content}


__all__ = [
    "assistant_text_item",
    "developer_message",
    "normalize_user_blocks",
    "user_blocks_to_responses_items",
]

# === core/markers.py ===
"""Helpers for encoding/decoding hidden response markers."""

import re
import secrets
from typing import Any

ULID_LENGTH = 16
_CROCKFORD_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
_SENTINEL = "[openai_responses:v2:"
_MARKER_RE = re.compile(
    r"\[openai_responses:v2:(?P<kind>[a-z0-9_]{2,30}):(?P<ulid>[A-Z0-9]{16})(?:\?(?P<query>[^\]]+))?\]:\s*#",
    re.I,
)


def generate_item_id() -> str:
    """Generate a short ULID-like identifier."""

    return "".join(secrets.choice(_CROCKFORD_ALPHABET) for _ in range(ULID_LENGTH))


def _qs(metadata: dict[str, str]) -> str:
    return "&".join(f"{key}={value}" for key, value in metadata.items()) if metadata else ""


def _parse_qs(query: str) -> dict[str, str]:
    return dict(part.split("=", 1) for part in query.split("&")) if query else {}


def create_marker(
    item_type: str,
    *,
    ulid: str | None = None,
    model_id: str | None = None,
    metadata: dict[str, str] | None = None,
) -> str:
    """Create a bare marker payload (without the wrapping newlines)."""

    if not re.fullmatch(r"[a-z0-9_]{2,30}", item_type):
        raise ValueError("item_type must be 2-30 chars of [a-z0-9_]")

    meta = {**(metadata or {})}
    if model_id:
        meta["model"] = model_id

    base = f"openai_responses:v2:{item_type}:{ulid or generate_item_id()}"
    return f"{base}?{_qs(meta)}" if meta else base


def wrap_marker(marker: str) -> str:
    """Wrap a marker string in an empty markdown link."""

    return f"\n[{marker}]: #\n"


def contains_marker(text: str) -> bool:
    """Return True if the sentinel substring is present."""

    return _SENTINEL in text


def parse_marker(marker: str) -> dict[str, Any]:
    """Parse a raw marker string back into its components."""

    if not marker.startswith("openai_responses:v2:"):
        raise ValueError("not a v2 marker")
    _, _, kind, rest = marker.split(":", 3)
    uid, _, query = rest.partition("?")
    return {"version": "v2", "item_type": kind, "ulid": uid, "metadata": _parse_qs(query)}


def extract_markers(text: str, *, parsed: bool = False) -> list[Any]:
    """Extract hidden markers from the assistant text."""

    found: list[Any] = []
    for match in _MARKER_RE.finditer(text):
        raw = f"openai_responses:v2:{match.group('kind')}:{match.group('ulid')}"
        if match.group("query"):
            raw += f"?{match.group('query')}"
        found.append(parse_marker(raw) if parsed else raw)
    return found


def split_text_by_markers(text: str) -> list[dict[str, str]]:
    """Split text into a list of literal segments and marker segments."""

    segments: list[dict[str, str]] = []
    last = 0
    for match in _MARKER_RE.finditer(text):
        if match.start() > last:
            segments.append({"type": "text", "text": text[last : match.start()]})
        raw = f"openai_responses:v2:{match.group('kind')}:{match.group('ulid')}"
        if match.group("query"):
            raw += f"?{match.group('query')}"
        segments.append({"type": "marker", "marker": raw})
        last = match.end()
    if last < len(text):
        segments.append({"type": "text", "text": text[last:]})
    return segments

# === core/errors.py ===
"""Typed exceptions referenced throughout the manifold."""


class ManifoldError(Exception):
    """Base class for manifold-specific exceptions."""


class ToolExecutionError(ManifoldError):
    """Raised when a tool invocation fails."""


class RoutingError(ManifoldError):
    """Raised when an automatic model routing step fails."""


class OpenAIStreamError(ManifoldError):
    """Raised when streaming events from OpenAI encounters a fatal error."""


class PersistenceError(ManifoldError):
    """Raised when items fail to persist or resolve."""


__all__ = [
    "ManifoldError",
    "OpenAIStreamError",
    "PersistenceError",
    "RoutingError",
    "ToolExecutionError",
]

# === services/history.py ===
"""Persistence and reconstruction services for Responses items."""

from typing import Any, Callable

# [build.py] internal imports removed in monolith:
# from ..core.markers import (
#     contains_marker,
#     create_marker,
#     extract_markers,
#     parse_marker,
#     split_text_by_markers,
#     wrap_marker,
# )
# from ..core.messages import (
#     assistant_text_item,
#     developer_message,
#     normalize_user_blocks,
#     user_blocks_to_responses_items,
# )
# from ..infra.openwebui_store import ItemStore

Resolver = Callable[[list[str], str | None, str | None], dict[str, dict[str, Any]]]


class HistoryPersistence:
    """Persist structured output items and emit hidden markers."""

    def __init__(self, store: ItemStore) -> None:
        self.store = store

    def persist_items_for_message(
        self,
        chat_id: str,
        message_id: str,
        items: list[dict[str, Any]],
        *,
        model_id: str,
    ) -> str:
        if not items:
            return ""

        ulids = self.store.save_items(chat_id, message_id, items, model_id)
        hidden_markers: list[str] = []
        for ulid, payload in zip(ulids, items):
            marker = create_marker(payload.get("type", "unknown"), ulid=ulid, model_id=model_id)
            hidden_markers.append(wrap_marker(marker))
        return "".join(hidden_markers)


class HistoryBuilder:
    """Rebuild Responses input items from OpenWebUI messages."""

    def __init__(self, resolve_items: Resolver | None = None) -> None:
        self._resolve_items = resolve_items

    def build_input_from_messages(
        self,
        messages: list[dict[str, Any]],
        *,
        chat_id: str | None = None,
        openwebui_model_id: str | None = None,
    ) -> list[dict[str, Any]]:
        required_item_ids: list[str] = []
        for message in messages:
            content = message.get("content")
            if message.get("role") == "assistant" and isinstance(content, str) and contains_marker(content):
                for marker in extract_markers(content, parsed=True):
                    required_item_ids.append(marker["ulid"])

        resolved: dict[str, dict[str, Any]] = {}
        if required_item_ids and self._resolve_items:
            resolved = self._resolve_items(required_item_ids, chat_id, openwebui_model_id)

        openai_input: list[dict[str, Any]] = []
        for message in messages:
            role = message.get("role")
            content = message.get("content")

            if role == "system":
                continue
            if role == "user":
                blocks = user_blocks_to_responses_items(normalize_user_blocks(content))
                if blocks:
                    openai_input.append({"role": "user", "content": blocks})
                continue
            if role == "developer":
                if isinstance(content, str) and content:
                    openai_input.append(developer_message(content))
                continue
            if role == "assistant" and isinstance(content, str):
                if not contains_marker(content):
                    if content.strip():
                        openai_input.append(assistant_text_item(content.strip()))
                    continue
                for segment in split_text_by_markers(content):
                    if segment["type"] == "marker":
                        marker = parse_marker(segment["marker"])
                        payload = resolved.get(marker["ulid"])
                        if payload:
                            openai_input.append(payload)
                    elif segment["type"] == "text":
                        text_segment = segment.get("text", "").strip()
                        if text_segment:
                            openai_input.append(assistant_text_item(text_segment))

        return openai_input


__all__ = ["HistoryBuilder", "HistoryPersistence"]

# === services/tools.py ===
"""Tool declaration and execution helpers."""

import asyncio
import inspect
import json
import logging
from typing import Any

# [build.py] internal imports removed in monolith:
# from ..core.api_models import ResponsesBody
# from ..core.capabilities import supports
# from ..core.errors import ToolExecutionError

logger = logging.getLogger(__name__)


def build_tools(
    responses_body: ResponsesBody,
    valves: Any,
    openwebui_tools: dict[str, Any] | None = None,
    *,
    features: dict[str, Any] | None = None,
    extra_tools: list[dict[str, Any]] | None = None,
) -> list[dict[str, Any]]:
    """Build the OpenAI Responses-API tool spec list for this request."""

    features = features or {}
    if not supports("function_calling", responses_body.model):
        return []

    tools: list[dict[str, Any]] = []
    tools.extend(_transform_owui_tools(openwebui_tools, strict=getattr(valves, "ENABLE_STRICT_TOOL_CALLING", False)))

    allow_web = (
        supports("web_search_tool", responses_body.model)
        and (getattr(valves, "ENABLE_WEB_SEARCH_TOOL", False) or features.get("web_search", False))
        and ((responses_body.reasoning or {}).get("effort", "").lower() != "minimal")
    )
    if allow_web:
        web_search_tool: dict[str, Any] = {
            "type": "web_search",
            "search_context_size": getattr(valves, "WEB_SEARCH_CONTEXT_SIZE", "medium"),
        }
        user_location = getattr(valves, "WEB_SEARCH_USER_LOCATION", None)
        if user_location:
            try:
                web_search_tool["user_location"] = json.loads(user_location)
            except Exception as exc:
                logger.warning("WEB_SEARCH_USER_LOCATION is not valid JSON; ignoring: %s", exc)
        tools.append(web_search_tool)

    remote_mcp = getattr(valves, "REMOTE_MCP_SERVERS_JSON", None)
    if remote_mcp:
        tools.extend(_build_mcp_tools(remote_mcp))

    if isinstance(extra_tools, list) and extra_tools:
        tools.extend(extra_tools)

    return _dedupe_tools(tools)


async def execute_tool_calls(
    calls: list[dict[str, Any]],
    registry: dict[str, dict[str, Any]],
) -> list[dict[str, Any]]:
    """Execute tool calls and return Responses-ready outputs."""

    async def _invoke(call: dict[str, Any]) -> tuple[dict[str, Any], str]:
        name = call.get("name")
        arguments_json = call.get("arguments", "{}")
        try:
            args = json.loads(arguments_json)
        except Exception as exc:  # pragma: no cover - defensive
            raise ToolExecutionError(f"Invalid JSON arguments for tool {name}: {exc}") from exc

        tool_cfg = registry.get(name)
        if not tool_cfg:
            return call, f"Tool '{name}' not found"

        fn = tool_cfg.get("callable")
        if not callable(fn):
            return call, f"Tool '{name}' is not callable"

        try:
            if inspect.iscoroutinefunction(fn):
                result = await fn(**args)
            else:
                result = await asyncio.to_thread(fn, **args)
        except Exception as exc:
            logger.warning("Tool %s raised an exception: %s", name, exc)
            return call, f"{type(exc).__name__}: {exc}"

        return call, str(result)

    results = await asyncio.gather(*(_invoke(call) for call in calls))
    outputs: list[dict[str, Any]] = []
    for call, output in results:
        outputs.append(
            {
                "type": "function_call_output",
                "call_id": call.get("call_id"),
                "output": output,
            }
        )
    return outputs


def _transform_owui_tools(
    openwebui_tools: dict[str, dict[str, Any]] | None,
    *,
    strict: bool = False,
) -> list[dict[str, Any]]:
    if not openwebui_tools:
        return []

    tools: list[dict[str, Any]] = []
    for item in openwebui_tools.values():
        spec = item.get("spec") or {}
        name = spec.get("name")
        if not name:
            continue

        params = spec.get("parameters") or {"type": "object", "properties": {}}
        tool = {
            "type": "function",
            "name": name,
            "description": spec.get("description") or name,
            "parameters": _strictify_schema(params) if strict else params,
        }
        if strict:
            tool["strict"] = True
        tools.append(tool)
    return tools


def _strictify_schema(schema: Any) -> dict[str, Any]:
    if not isinstance(schema, dict):
        return {}

    data = json.loads(json.dumps(schema))

    def _enforce(node: dict[str, Any]) -> None:
        node_type = node.get("type")
        is_object = (
            node_type == "object"
            or (isinstance(node_type, list) and "object" in node_type)
            or "properties" in node
        )
        if is_object:
            props = node.setdefault("properties", {})
            if not isinstance(props, dict):
                props = {}
                node["properties"] = props

            original_required = set(node.get("required") or [])
            node["additionalProperties"] = False
            node["required"] = list(props.keys())

            for name, prop in props.items():
                if not isinstance(prop, dict):
                    continue
                if name not in original_required:
                    ptype = prop.get("type")
                    if isinstance(ptype, str) and ptype != "null":
                        prop["type"] = [ptype, "null"]
                    elif isinstance(ptype, list) and "null" not in ptype:
                        prop["type"] = [*ptype, "null"]
                _enforce(prop)

        items = node.get("items")
        if isinstance(items, dict):
            _enforce(items)
        elif isinstance(items, list):
            for entry in items:
                if isinstance(entry, dict):
                    _enforce(entry)

        for key in ("anyOf", "oneOf"):
            branches = node.get(key)
            if isinstance(branches, list):
                for branch in branches:
                    if isinstance(branch, dict):
                        _enforce(branch)

    _enforce(data)
    return data


def _build_mcp_tools(mcp_json: str) -> list[dict[str, Any]]:
    try:
        parsed = json.loads(mcp_json)
    except Exception as exc:  # pragma: no cover - valved bug
        logger.warning("REMOTE_MCP_SERVERS_JSON is not valid JSON: %s", exc)
        return []

    entries = parsed if isinstance(parsed, list) else [parsed]
    tools: list[dict[str, Any]] = []
    for item in entries:
        if not isinstance(item, dict):
            continue
        tool = {
            "type": "mcp",
            "server_label": item.get("server_label"),
            "server_url": item.get("server_url"),
        }
        for key in (
            "model_preference",
            "client_capabilities",
            "require_approval",
            "allowed_tools",
        ):
            if key in item:
                tool[key] = item[key]
        tools.append(tool)
    return tools


def _dedupe_tools(tools: list[dict[str, Any]] | None) -> list[dict[str, Any]]:
    if not tools:
        return []

    seen: dict[tuple[str, str | None], dict[str, Any]] = {}
    for tool in tools:
        tool_type = tool.get("type")
        if not isinstance(tool_type, str):
            continue
        identifier: str | None = None
        if tool_type == "function":
            name = tool.get("name")
            if isinstance(name, str):
                identifier = name
        seen[(tool_type, identifier)] = tool
    return list(seen.values())


__all__ = ["build_tools", "execute_tool_calls"]

# === services/routing.py ===
"""Helper model routing for auto variants."""

import json
import logging
from collections.abc import Awaitable, Callable
from typing import Any

# [build.py] internal imports removed in monolith:
# from ..core.api_models import ResponsesBody
# from ..utils import emit_status
# from ..infra.openai_client import OpenAIResponsesClient

EventEmitter = Callable[[dict[str, Any]], Awaitable[None]]

logger = logging.getLogger(__name__)


async def route_auto_model(
    client: OpenAIResponsesClient,
    *,
    router_model: str,
    responses_body: ResponsesBody,
    valves: Any,
    tools: list[dict[str, Any]],
    event_emitter: EventEmitter | None = None,
) -> ResponsesBody:
    """
    Use a small helper model to choose the final GPT-5 variant and reasoning effort.

    The helper request mirrors the structure described in the Developer Guide v2.
    """

    router_body = {
        "model": router_model,
        "reasoning": {"effort": "minimal"},
        "instructions": _ROUTER_PROMPT,
        "input": responses_body.input,
        "prompt_cache_key": "openai_responses_gpt5-router",
        "text": {
            "format": {
                "type": "json_schema",
                "name": "gpt5_router",
                "strict": True,
                "schema": _ROUTER_SCHEMA,
                "verbosity": "medium",
            },
        },
    }

    try:
        response = await client.create(
            router_body,
            api_key=valves.API_KEY,
            base_url=valves.BASE_URL,
        )
    except Exception as exc:  # pragma: no cover
        logger.warning("Model router request failed: %s", exc)
        return responses_body

    text = _extract_router_text(response)
    if not text:
        return responses_body

    try:
        router_json: dict[str, Any] = json.loads(text)
    except Exception:
        start, end = text.find("{"), text.rfind("}")
        router_json = (
            json.loads(text[start : end + 1]) if start != -1 and end != -1 and end > start else {}
        )

    if not router_json:
        return responses_body

    model_choice = router_json.get("model")
    if isinstance(model_choice, str):
        responses_body.model = model_choice
    effort = router_json.get("reasoning_effort")
    if isinstance(effort, str):
        reasoning = dict(responses_body.reasoning or {})
        reasoning["effort"] = effort
        responses_body.reasoning = reasoning

    responses_body.model_router_result = router_json
    explanation = router_json.get("explanation")
    if isinstance(explanation, str):
        await emit_status(
            event_emitter,
            f"Routing to {router_json.get('model')} (effort: {router_json.get('reasoning_effort')})\nExplanation: {explanation}",
        )
    return responses_body


def _extract_router_text(response: dict[str, Any]) -> str:
    try:
        return next(
            (
                block["text"]
                for output in reversed(response["output"])
                if output["type"] == "message"
                for block in output["content"]
                if block["type"] == "output_text"
            ),
            "",
        )
    except Exception as exc:  # pragma: no cover
        logger.warning(
            "Router response missing expected fields: %s; payload keys=%s",
            exc,
            list(response.keys()),
        )
        return ""


_ROUTER_SCHEMA = {
    "type": "object",
    "properties": {
        "model": {
            "type": "string",
            "enum": ["gpt-5-chat-latest", "gpt-5", "gpt-5-mini"],
        },
        "reasoning_effort": {
            "type": "string",
            "enum": ["minimal", "low", "medium", "high"],
        },
        "explanation": {
            "type": "string",
            "minLength": 3,
            "maxLength": 500,
        },
    },
    "required": ["model", "explanation", "reasoning_effort"],
    "additionalProperties": False,
}

_ROUTER_PROMPT = """# Role and Objective
Serve as a **routing helper** for selecting the most appropriate GPT-5 model for user messages, evaluating tool necessity and task complexity.

---

# Instructions
- If a message may require the use of **any available tool**, select a model with **function calling** capabilities. If **web search** is required, you may only choose **low, medium or high** reasoning, not minimal.
- When tools are not necessary, favor the **fastest** or **most capable** model according to the complexity of the request.

---

# Available Models and Capabilities
## Models

- **gpt-5-chat-latest**
  - Fast, general-purpose, and creative.
  - Best for writing, drafting, and chat-based interactions.
  - ⚠️ Does **not** support tool calling—select only when tools are not required.

- **gpt-5-mini**
  - Lightweight, supports tool usage, and is rapidly responsive.
  - Suited for **simple tasks that may use tools** but don't demand extensive reasoning.
  - ✅ Function calling supported—offers a strong balance between speed and utility.

- **gpt-5**
  - Strong at reasoning and complex, multi-step analysis.
  - Designed for **complex or deeply analytical tasks**.
  - ✅ Supports function calling and advanced operations—choose for tool-reliant or high-complexity reasoning needs.

---

# Routing Checklist
- Assess whether tool integration could improve the response.
- Evaluate how much reasoning or problem-solving is required.
- Match model to requirements:
  - No tool usage required → use `gpt-5-chat-latest`
  - Tools required, simple task → use `gpt-5-mini`
  - Tools required, complex task → use `gpt-5`
- When in doubt, prioritize a tool-capable model (prefer `gpt-5`).
- Ask for more information if requirements are ambiguous.

---

# Output Format
Respond only with a JSON object containing your model selection and a concise explanation. If the requirements are unclear, include an appropriate error message in the JSON response.

---

# Examples
- **What's the weather in Vancouver right now?**
  ```json
  {
    "model": "gpt-5-mini",
    "explanation": "Quick tool lookup; simple enough for a fast model."
  }
  ```

- **Compare the newest M3 laptops and cite sources.**
  ```json
  {
    "model": "gpt-5",
    "explanation": "Research and synthesis with tools requires reasoning depth."
  }
  ```

- **Summarize this email draft and make it more formal.**
  ```json
  {
    "model": "gpt-5-chat-latest",
    "explanation": "Polishing text only; no tools needed."
  }
  ```

- **Summarize this uploaded PDF into bullet points.**
  ```json
  {
    "model": "gpt-5",
    "explanation": "Document parsing may require tools; complex enough for gpt-5."
  }
  ```

- **Translate this paragraph into Spanish.**
  ```json
  {
    "model": "gpt-5-chat-latest",
    "explanation": "Simple translation; tools not required."
  }
  ```

- **List my upcoming meetings tomorrow.**
  ```json
  {
    "model": "gpt-5-mini",
    "explanation": "Calendar tool lookup is simple; mini is efficient."
  }
  ```
"""

__all__ = ["route_auto_model"]

# === infra/openwebui_store.py ===
"""Persistence helpers for storing Responses items in OpenWebUI."""

import datetime
import secrets
from typing import Any

from open_webui.models.chats import Chats

_CROCKFORD = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"


class ItemStore:
    """Adapter around ``open_webui.models.chats.Chats``."""

    def __init__(self, *, store_key: str = "openai_responses_pipe") -> None:
        self.store_key = store_key

    def save_items(
        self,
        chat_id: str,
        message_id: str,
        items: list[dict[str, Any]],
        model_id: str,
    ) -> list[str]:
        """Persist items and return the generated ULIDs."""

        if not items:
            return []

        chat_model = Chats.get_chat_by_id(chat_id)
        if not chat_model:
            return []

        pipe_root = chat_model.chat.setdefault(self.store_key, {"__v": 3})
        items_store = pipe_root.setdefault("items", {})
        messages_index = pipe_root.setdefault("messages_index", {})
        message_bucket = messages_index.setdefault(
            message_id,
            {"role": "assistant", "done": True, "item_ids": []},
        )

        now = int(datetime.datetime.now(datetime.UTC).timestamp())
        stored_ids: list[str] = []
        for payload in items:
            item_id = _generate_item_id()
            items_store[item_id] = {
                "model": model_id,
                "created_at": now,
                "payload": payload,
                "message_id": message_id,
            }
            message_bucket["item_ids"].append(item_id)
            stored_ids.append(item_id)

        Chats.update_chat_by_id(chat_id, chat_model.chat)
        return stored_ids

    def load_items(
        self,
        chat_id: str,
        item_ids: list[str],
        *,
        model_id: str | None = None,
    ) -> dict[str, dict[str, Any]]:
        """Fetch persisted items by ULID, optionally filtered by model id."""

        if not item_ids:
            return {}
        chat_model = Chats.get_chat_by_id(chat_id)
        if not chat_model:
            return {}

        items_store = chat_model.chat.get(self.store_key, {}).get("items", {})
        lookup: dict[str, dict[str, Any]] = {}
        for item_id in item_ids:
            item = items_store.get(item_id)
            if not item:
                continue
            if model_id and item.get("model") != model_id:
                continue
            payload = item.get("payload")
            if isinstance(payload, dict):
                lookup[item_id] = payload
        return lookup


def _generate_item_id(length: int = 16) -> str:
    return "".join(secrets.choice(_CROCKFORD) for _ in range(length))


__all__ = ["ItemStore"]

# === infra/openai_client.py ===
"""aiohttp-backed client for the OpenAI Responses API."""

import json
import logging
from collections.abc import AsyncIterator
from typing import Any

import aiohttp


class OpenAIResponsesClient:
    """Thin wrapper around ``aiohttp`` with SDK-like method names."""

    def __init__(self) -> None:
        self._session: aiohttp.ClientSession | None = None
        self._logger = logging.getLogger(__name__)

    async def stream(
        self,
        request_body: dict[str, Any],
        *,
        api_key: str,
        base_url: str,
    ) -> AsyncIterator[dict[str, Any]]:
        """Yield SSE events from ``POST /responses``."""

        session = await self._get_or_init_http_session()
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "Accept": "text/event-stream",
        }
        url = base_url.rstrip("/") + "/responses"

        buf = bytearray()
        async with session.post(url, json=request_body, headers=headers) as resp:
            resp.raise_for_status()

            async for chunk in resp.content.iter_chunked(4096):
                buf.extend(chunk)
                start_idx = 0
                while True:
                    newline_idx = buf.find(b"\n", start_idx)
                    if newline_idx == -1:
                        break
                    line = buf[start_idx:newline_idx].strip()
                    start_idx = newline_idx + 1
                    if not line or line.startswith(b":") or not line.startswith(b"data:"):
                        continue
                    payload = line[5:].strip()
                    if payload == b"[DONE]":
                        return
                    yield json.loads(payload.decode("utf-8"))
                if start_idx > 0:
                    del buf[:start_idx]

    async def create(
        self,
        request_body: dict[str, Any],
        *,
        api_key: str,
        base_url: str,
    ) -> dict[str, Any]:
        """Send a non-streaming request to ``POST /responses``."""

        session = await self._get_or_init_http_session()
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }
        url = base_url.rstrip("/") + "/responses"
        async with session.post(url, json=request_body, headers=headers) as resp:
            resp.raise_for_status()
            return await resp.json()

    async def close(self) -> None:
        """Close the underlying client session."""

        if self._session and not self._session.closed:
            await self._session.close()

    async def _get_or_init_http_session(self) -> aiohttp.ClientSession:
        if self._session is not None and not self._session.closed:
            self._logger.debug("Reusing existing aiohttp session")
            return self._session

        connector = aiohttp.TCPConnector(
            limit=50,
            limit_per_host=10,
            keepalive_timeout=75,
            ttl_dns_cache=300,
        )
        timeout = aiohttp.ClientTimeout(
            connect=30,
            sock_connect=30,
            sock_read=3600,
        )
        self._logger.debug("Creating new aiohttp session")
        self._session = aiohttp.ClientSession(
            connector=connector,
            timeout=timeout,
            json_serialize=json.dumps,
        )
        return self._session


__all__ = ["OpenAIResponsesClient"]

# === utils/logging.py ===
"""Session-scoped logging helpers with a single namespace and context injection."""

import logging
import sys
from collections import defaultdict, deque
from contextlib import contextmanager
from contextvars import ContextVar, Token
from typing import Any, DefaultDict, Deque, Iterator, Tuple

# ---------------------------------------------------------------------------
# Context and buffering
# ---------------------------------------------------------------------------

current_session_id: ContextVar[str | None] = ContextVar(
    "openai_responses_session_id", default=None
)
current_chat_id: ContextVar[str | None] = ContextVar(
    "openai_responses_chat_id", default=None
)
current_message_id: ContextVar[str | None] = ContextVar(
    "openai_responses_message_id", default=None
)
current_user_id: ContextVar[str | None] = ContextVar(
    "openai_responses_user_id", default=None
)
current_log_level: ContextVar[int] = ContextVar(
    "openai_responses_log_level", default=logging.INFO
)

SESSION_LOGS: DefaultDict[str, Deque[str]] = defaultdict(lambda: deque(maxlen=2000))


class _ContextFilter(logging.Filter):
    """Attach session/chat/message/user context and enforce the current log level."""

    def filter(self, record: logging.LogRecord) -> bool:  # noqa: D401
        record.session_id = current_session_id.get()
        record.chat_id = current_chat_id.get()
        record.message_id = current_message_id.get()
        record.user_id = current_user_id.get()
        return record.levelno >= current_log_level.get()


class _MemoryHandler(logging.Handler):
    """Buffer log lines per session for later citation emission."""

    def emit(self, record: logging.LogRecord) -> None:  # pragma: no cover
        session = getattr(record, "session_id", None)
        if not session:
            return
        SESSION_LOGS[session].append(self.format(record))


_configured = False
_context_filter = _ContextFilter()
_LOG_FORMAT = (
    "%(asctime)s [%(levelname)s] %(message)s "
    "session_id=%(session_id)s chat_id=%(chat_id)s message_id=%(message_id)s user_id=%(user_id)s"
)


def configure_logging() -> None:
    """Attach console + memory handlers once under the canonical namespace."""

    global _configured
    if _configured:
        return

    logger = logging.getLogger("openai_responses_manifold")
    logger.setLevel(logging.DEBUG)
    logger.propagate = False

    formatter = logging.Formatter(_LOG_FORMAT)

    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setLevel(logging.DEBUG)
    console_handler.setFormatter(formatter)
    console_handler.addFilter(_context_filter)

    memory_handler = _MemoryHandler()
    memory_handler.setLevel(logging.DEBUG)
    memory_handler.setFormatter(formatter)
    memory_handler.addFilter(_context_filter)

    logger.addHandler(console_handler)
    logger.addHandler(memory_handler)
    logger.addFilter(_context_filter)

    _configured = True


def set_session(
    session_id: str | None,
    level: int,
    *,
    chat_id: str | None = None,
    message_id: str | None = None,
    user_id: str | None = None,
) -> Tuple[Token[str | None], Token[str | None], Token[str | None], Token[str | None], Token[int]]:
    """Set session/log-level ContextVars and return reset tokens."""

    configure_logging()
    token_session = current_session_id.set(session_id)
    token_chat = current_chat_id.set(chat_id)
    token_message = current_message_id.set(message_id)
    token_user = current_user_id.set(user_id)
    token_level = current_log_level.set(level)
    return token_session, token_chat, token_message, token_user, token_level


def reset_session(
    tokens: Tuple[Token[str | None], Token[str | None], Token[str | None], Token[str | None], Token[int]]
) -> None:
    """Reset ContextVars using tokens from ``set_session``."""

    token_session, token_chat, token_message, token_user, token_level = tokens
    current_session_id.reset(token_session)
    current_chat_id.reset(token_chat)
    current_message_id.reset(token_message)
    current_user_id.reset(token_user)
    current_log_level.reset(token_level)


def get_session_logs(session_id: str | None) -> list[str]:
    if not session_id:
        return []
    return list(SESSION_LOGS.get(session_id, ()))


def clear_session_logs(session_id: str | None) -> None:
    if not session_id:
        return
    SESSION_LOGS.pop(session_id, None)


def consume_session_logs(session_id: str | None) -> list[str]:
    lines = get_session_logs(session_id)
    clear_session_logs(session_id)
    return lines


@contextmanager
def session_logging(
    session_id: str | None,
    level: int,
    *,
    chat_id: str | None = None,
    message_id: str | None = None,
    user_id: str | None = None,
) -> Iterator[None]:
    tokens = set_session(
        session_id,
        level,
        chat_id=chat_id,
        message_id=message_id,
        user_id=user_id,
    )
    try:
        yield
    finally:
        reset_session(tokens)


class SessionLogger:
    """Thin facade around the session-aware logging helpers."""

    session_id = current_session_id
    chat_id = current_chat_id
    message_id = current_message_id
    user_id = current_user_id
    log_level = current_log_level
    logs = SESSION_LOGS

    get_session_logs = staticmethod(get_session_logs)
    clear_session_logs = staticmethod(clear_session_logs)
    consume_session_logs = staticmethod(consume_session_logs)
    set_session = staticmethod(set_session)
    reset_session = staticmethod(reset_session)
    session_logging = staticmethod(session_logging)

    @classmethod
    def get_logger(cls, name: str = __name__) -> logging.Logger:
        configure_logging()
        base = "openai_responses_manifold"
        qualified = name if name.startswith(base) else f"{base}.{name}"
        return logging.getLogger(qualified)


def truncate_for_log(value: Any, limit: int = 2000) -> tuple[str, bool]:
    """Return a safe, possibly truncated string for logging."""

    if value is None:
        return "", False
    text = value if isinstance(value, str) else str(value)
    if len(text) <= limit:
        return text, False
    return text[:limit], True


# Configure immediately so children inherit handlers/filters.
configure_logging()


__all__ = [
    "SessionLogger",
    "clear_session_logs",
    "configure_logging",
    "consume_session_logs",
    "current_log_level",
    "current_chat_id",
    "current_message_id",
    "current_session_id",
    "current_user_id",
    "get_session_logs",
    "reset_session",
    "session_logging",
    "set_session",
    "truncate_for_log",
]

# === utils/events.py ===
"""Utility functions for emitting OpenWebUI events."""

from collections.abc import Awaitable, Callable
from typing import Any

EventEmitter = Callable[[dict[str, Any]], Awaitable[None]]


def wrap_event_emitter(
    emitter: EventEmitter | None,
    *,
    suppress_chat_messages: bool = False,
    suppress_completion: bool = False,
) -> EventEmitter:
    """Wrap the given event emitter and optionally suppress certain event types."""

    if emitter is None:

        async def _noop(_: dict[str, Any]) -> None:
            return

        return _noop

    async def _wrapped(event: dict[str, Any]) -> None:
        event_type = (event or {}).get("type")
        if suppress_chat_messages and event_type == "chat:message":
            return
        if suppress_completion and event_type == "chat:completion":
            return
        await emitter(event)

    return _wrapped


async def emit_status(
    emitter: EventEmitter | None,
    description: str,
    *,
    action: str | None = None,
    **extra: Any,
) -> None:
    if emitter is None:
        return
    payload = {"description": description}
    if action:
        payload["action"] = action
    payload.update(extra)
    await emitter({"type": "status", "data": payload})


async def emit_chat_message(
    emitter: EventEmitter | None,
    content: str,
    *,
    options: dict[str, Any] | None = None,
) -> None:
    if emitter is None:
        return
    payload = {"content": content}
    if options:
        payload["options"] = options
    await emitter({"type": "chat:message", "data": payload})


async def emit_completion(
    emitter: EventEmitter | None,
    *,
    content: str | None = "",
    title: str | None = None,
    usage: dict[str, Any] | None = None,
    error: dict[str, Any] | None = None,
    done: bool = True,
) -> None:
    if emitter is None:
        return
    data: dict[str, Any] = {"done": done}
    if content is not None:
        data["content"] = content
    if title is not None:
        data["title"] = title
    if usage is not None:
        data["usage"] = usage
    if error is not None:
        data["error"] = error
    await emitter({"type": "chat:completion", "data": data})


async def emit_usage_delta(
    emitter: EventEmitter | None,
    usage: dict[str, Any],
) -> None:
    if emitter is None or not usage:
        return
    await emitter({"type": "usage", "data": usage})


async def emit_citation(
    emitter: EventEmitter | None,
    document: str | list[str],
    source_name: str,
    *,
    metadata: dict[str, Any] | None = None,
) -> None:
    if emitter is None:
        return
    if isinstance(document, list):
        doc_text = "\n".join(document)
    else:
        doc_text = document
    await emitter(
        {
            "type": "citation",
            "data": {
                "document": [doc_text],
                "metadata": [
                    {
                        "source": source_name,
                        **(metadata or {}),
                    }
                ],
                "source": {"name": source_name},
            },
        }
    )


async def emit_error(
    emitter: EventEmitter | None,
    message: str,
    *,
    done: bool = False,
) -> None:
    """Emit a standard error completion event."""

    await emit_completion(emitter, error={"message": message}, done=done)


def merge_usage_stats(total: dict[str, Any], new: dict[str, Any]) -> dict[str, Any]:
    """Recursively merge nested usage dicts."""

    for key, value in new.items():
        if isinstance(value, dict):
            total[key] = merge_usage_stats(total.get(key, {}), value)
        elif isinstance(value, (int, float)):
            total[key] = total.get(key, 0) + value
        elif value is not None:
            total[key] = value
    return total


def wrap_code_block(text: str, language: str = "python") -> str:
    """Wrap a block of text in fenced markdown code."""

    return f"```{language}\n{text}\n```"


__all__ = [
    "EventEmitter",
    "emit_chat_message",
    "emit_citation",
    "emit_completion",
    "emit_error",
    "emit_status",
    "emit_usage_delta",
    "merge_usage_stats",
    "wrap_code_block",
    "wrap_event_emitter",
]

# fmt: on
